version: '3'
services:
  api:
    restart: always
    build: .
    ports:
      - 80:3000
    environment: 
      # Server port
      - PORT=3000
      # MongoDB
      - MONGO_URI=mongodb://database:27017/vozy
      - MONGO_URI_TEST=mongodb://database:27017/vozytest
      # JWT
      - JWT_SECRET=carlosarrieta
    depends_on:
      - database

  database:
    image: mongo
    ports:
      - 27020:27017
    volumes:
      - mongodb:/data/db
      
volumes:
 mongodb: